
source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-partial'
gem 'sinatra-session'
gem 'shotgun'
gem 'sqlite3'

